export const INLINE = {
  BOLD: 'BOLD',
  ITALIC: 'ITALIC',
  UNDERLINE: 'UNDERLINE'
};

export const BLOCK = {
  BULLET_LIST: 'BULLET_LIST',
  TITLE: 'TITLE',
  LIST_ITEM: 'LIST_ITEM',
  NUMBER_LIST: 'NUMBER_LIST',
  BLOCKQUOTE: 'BLOCKQUOTE',
  PARAGRAPH: 'PARAGRAPH',
  IMAGE: 'IMAGE'
};
